// <auto-generated />
using System;
using CoffeeShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251004141126_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CoffeeShop.Models.ChatMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatModelId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CoffeeShop.Models.ChatModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("CoffeeShop.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "robust",
                            Description = "One of the most popular coffees in the world', 'Brazilian coffee is famous for its balanced and approachable flavors. Most Brazilian beans lean towards a mild, nutty taste with hints of chocolate. Some regions, like Minas Gerais, produce coffee with a sweet, nutty profile, while areas like Bahia are known for their fruity, lively notes.",
                            Price = 29f,
                            QuantityOnHand = 5,
                            Title = "Brazilian Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Category = "robust",
                            Description = "Known for its balanced, smooth flavor and rich aroma. Colombian coffee is celebrated for its well-rounded flavor profile. It often features a smooth, medium body with a bright acidity and notes of citrus or red berries. The country's diverse geography allows for a wide range of flavor nuances, from the caramel sweetness of the Antioquia region to the vibrant fruitiness of Huila.",
                            Price = 5f,
                            QuantityOnHand = 0,
                            Title = "Colombian Coffee"
                        },
                        new
                        {
                            Id = 3,
                            Category = "robust",
                            Description = "A floral and citrusy coffee with a light body. Yirgacheffe coffee is a true gem of the coffee world. It is a wet-processed coffee with a distinctively clean, light body and a tea-like quality. Its flavor notes are predominantly floral, often with jasmine and bergamot, and a bright, citrusy acidity. It is known for its delicate and complex character.",
                            Price = 6f,
                            QuantityOnHand = 0,
                            Title = "Ethiopian Yirgacheffe"
                        },
                        new
                        {
                            Id = 4,
                            Category = "soft",
                            Description = "A vibrant coffee with bold fruit and wine notes. Kenyan coffee is highly sought after for its complex and lively flavor. The AA grade indicates a large bean size, often associated with higher quality. This coffee is known for its bright, sparkling acidity, full body, and rich, wine-like flavors, including notes of blackcurrant, tomato, and citrus. It has a powerful and memorable taste.",
                            Price = 7f,
                            QuantityOnHand = 0,
                            Title = "Kenyan AA"
                        },
                        new
                        {
                            Id = 5,
                            Category = "soft",
                            Description = "A full-bodied and earthy coffee from Indonesia. Sumatra Mandheling is renowned for its low acidity and heavy, syrupy body. This coffee has a unique flavor profile that is earthy and rustic, often with notes of chocolate, tropical fruit, and a distinct forest floor aroma. It is often wet-hulled, a process that gives it a signature earthy, spicy character and a smooth finish.",
                            Price = 13f,
                            QuantityOnHand = 2,
                            Title = "Sumatra Mandheling"
                        },
                        new
                        {
                            Id = 6,
                            Category = "intense",
                            Description = "A clean, crisp coffee with a classic balance. Tarrazu coffee is a high-altitude bean from Costa Rica, known for its superb quality and clean taste. It has a medium body, a delicate, bright acidity, and a smooth, mellow finish. Flavor notes typically include brown sugar, citrus, and hints of tropical fruit. It is a quintessential Central American coffee.",
                            Price = 9f,
                            QuantityOnHand = 4,
                            Title = "Costa Rican Tarrazu"
                        },
                        new
                        {
                            Id = 7,
                            Category = "soft",
                            Description = "A full-bodied coffee with a smoky, chocolatey flavor. Antigua coffee from Guatemala is grown in a volcanic region, which contributes to its rich, full-bodied character. It has a high-quality reputation, offering a complex flavor profile with notes of chocolate, spice, and a subtle smoky aroma. The acidity is bright and pleasant, and the finish is often spicy and prolonged.",
                            Price = 22f,
                            QuantityOnHand = 8,
                            Title = "Guatemalan Antigua"
                        },
                        new
                        {
                            Id = 8,
                            Category = "robust",
                            Description = "One of the world's most rare and expensive coffees. Jamaican Blue Mountain coffee is famous for its mild flavor and lack of bitterness. It has a well-balanced body, a clean, sweet taste, and a very smooth finish. Its flavor profile is often described as having notes of nuts and herbs, with a subtle sweetness. It is considered a premium, luxury coffee.",
                            Price = 8f,
                            QuantityOnHand = 0,
                            Title = "Jamaican Blue Mountain"
                        },
                        new
                        {
                            Id = 9,
                            Category = "intense",
                            Description = "A rare, delicate coffee with a smooth, bright flavor. Kona coffee is grown on the slopes of the Mauna Loa and Hualalai volcanoes in Hawaii. It is a smooth, light-bodied coffee with a complex aroma and a crisp, clean taste. Its flavor profile includes notes of milk chocolate, nuts, and fruit, with a low acidity and a sweet finish. It is prized for its rarity and consistent quality.",
                            Price = 17f,
                            QuantityOnHand = 0,
                            Title = "Hawaiian Kona"
                        },
                        new
                        {
                            Id = 10,
                            Category = "intense",
                            Description = "A strong, bold coffee with a high caffeine content. Robusta coffee from Vietnam is known for its powerful, full-bodied taste and is a staple in Vietnamese coffee culture. It has a nutty and chocolatey profile, with notes of caramel and a strong, bitter aftertaste. It is often prepared using a phin filter, resulting in a thick and intense brew, commonly served with sweetened condensed milk.",
                            Price = 12f,
                            QuantityOnHand = 0,
                            Title = "Vietnamese Robusta"
                        },
                        new
                        {
                            Id = 11,
                            Category = "arabic",
                            Description = "A bright, lively coffee with citrus and berry notes. Tanzanian Peaberry is a unique coffee where the cherry produces a single, round bean instead of two flat ones. This is believed to concentrate the flavor. The resulting cup has a rich, medium body with a vibrant, wine-like acidity. Flavor notes often include citrus, blackcurrant, and hints of cedar, offering a bright and sophisticated experience.",
                            Price = 11f,
                            QuantityOnHand = 9,
                            Title = "Tanzanian Peaberry"
                        },
                        new
                        {
                            Id = 12,
                            Category = "arabic",
                            Description = "One of the oldest and most historical coffees. Yemeni Mokha coffee has a distinct, rustic flavor profile. It has a full body and a deep, complex taste with notes of chocolate, fruit, and spice. The processing method, drying the cherries on rooftops, gives it a unique, earthy quality. It is known for its wild, untamed flavor and rich history, named after the port of Mokha.",
                            Price = 23f,
                            QuantityOnHand = 7,
                            Title = "Yemeni Mokha"
                        },
                        new
                        {
                            Id = 13,
                            Category = "arabic",
                            Description = "A sweet and floral coffee with a clean finish. Burundi coffee is gaining popularity for its excellent quality. Grown at high altitudes, it has a clean and bright profile. The flavor often includes notes of floral honey, citrus, and red berries, with a delicate acidity and a medium body. It offers a sweet and pleasant cup that is very approachable.",
                            Price = 23f,
                            QuantityOnHand = 6,
                            Title = "Burundi Coffee"
                        },
                        new
                        {
                            Id = 14,
                            Category = "arabic",
                            Description = "A wild, fruit-forward coffee with a complex profile. Ethiopian Harrar is a dry-processed coffee with a strong, fruity flavor. It has a heavy body and a low acidity, with a taste that is often described as wild and complex. Common notes include blueberries, cocoa, and spices. It is a bold and rustic coffee that stands out with its unique, naturally fruity taste.",
                            Price = 14f,
                            QuantityOnHand = 5,
                            Title = "Ethiopian Harrar"
                        },
                        new
                        {
                            Id = 15,
                            Category = "intense",
                            Description = "A coffee with a unique, earthy, and nutty character. Monsooned Malabar coffee is a specialty of the Malabar Coast of India. The beans are exposed to monsoon winds and rain for several months, which causes them to swell and lose their original acidity. The resulting coffee is very low in acidity with a unique, heavy body and a pungent, earthy, and nutty flavor.",
                            Price = 8f,
                            QuantityOnHand = 1,
                            Title = "Indian Monsooned Malabar"
                        });
                });

            modelBuilder.Entity("CoffeeShop.Models.ChatMessageModel", b =>
                {
                    b.HasOne("CoffeeShop.Models.ChatModel", "ChatModel")
                        .WithMany("Messages")
                        .HasForeignKey("ChatModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatModel");
                });

            modelBuilder.Entity("CoffeeShop.Models.ChatModel", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
